# Flux-RX Dashboard Module: Interactive Dash application
from __future__ import annotations

from typing import Optional

import pandas as pd
from dash import Dash, html, dcc, Input, Output, State, callback, no_update
import dash_bootstrap_components as dbc

from flux_rx.data import fetch, get_info, fetch_multiple, align_dataframes
from flux_rx.analytics import compute_metrics, format_metrics
from flux_rx.charts import (
    price_chart,
    drawdown_chart,
    rolling_vol_chart,
    rolling_sharpe_chart,
    monthly_heatmap,
    performance_chart,
    risk_return_scatter,
    correlation_matrix,
    cumulative_returns_chart,
    candlestick_chart,
)
from flux_rx.themes import get_theme, list_themes, DEFAULT_THEME


def create_app(
    default_tickers: Optional[list[str]] = None,
    default_theme: str = DEFAULT_THEME,
) -> Dash:
    app = Dash(
        __name__,
        external_stylesheets=[dbc.themes.BOOTSTRAP],
        suppress_callback_exceptions=True,
        title="Flux-RX Dashboard",
    )
    
    if default_tickers is None:
        default_tickers = ["SPY"]
    
    app.layout = html.Div([
        dbc.Container([
            html.Div([
                html.Div([
                    html.H1("Flux-RX", style={"color": "#58a6ff", "fontWeight": "800", "marginBottom": "0"}),
                    html.P("v1.0.0 Terminal", style={"color": "#8b949e", "fontSize": "12px"}),
                ]),
                html.Div([
                    html.Label("Global Theme", style={"color": "#8b949e", "fontSize": "11px", "textTransform": "uppercase"}),
                    dcc.Dropdown(
                        id="global-theme-selector",
                        options=[{"label": t.title(), "value": t} for t in list_themes()],
                        value=default_theme,
                        clearable=False,
                        style={"width": "150px"}
                    ),
                ], style={"display": "flex", "flexDirection": "column", "alignItems": "flex-end"}),
            ], style={"display": "flex", "justifyContent": "space-between", "alignItems": "center", "marginBottom": "32px", "paddingBottom": "16px", "borderBottom": "1px solid #30363d"}),
            
            dbc.Tabs([
                dbc.Tab(label="Single Ticker Analysis", tab_id="tab-single"),
                dbc.Tab(label="Multi-Ticker Comparison", tab_id="tab-compare"),
            ], id="tabs", active_tab="tab-single", style={"marginBottom": "24px"}),
            
            html.Div(id="tab-content"),
            
            html.Footer([
                html.P("Generated by Flux-RX Engine", style={"color": "#8b949e", "fontSize": "11px", "marginTop": "48px", "textAlign": "center"}),
            ])
        ], fluid=True, style={"padding": "32px", "backgroundColor": "#0d1117", "minHeight": "100vh"})
    ])
    
    @app.callback(
        Output("tab-content", "children"),
        [Input("tabs", "active_tab")],
    )
    def render_content(active_tab):
        if active_tab == "tab-single":
            return render_single_tab()
        return render_compare_tab()

    @app.callback(
        [Output("single-metrics-summary", "children"),
         Output("single-charts-container", "children")],
        [Input("analyze-btn", "n_clicks")],
        [State("ticker-input", "value"),
         State("period-selector", "value"),
         State("global-theme-selector", "value")],
    )
    def update_single(n_clicks, ticker, period, theme):
        if not ticker: return no_update
        ticker = ticker.upper().strip()
        try:
            df = fetch(ticker, period=period)
            metrics = compute_metrics(df["Close"])
            formatted = format_metrics(metrics)
            
            summary = dbc.Row([
                dbc.Col(dbc.Card([
                    dbc.CardBody([
                        html.H6("CAGR", className="card-subtitle mb-2 text-muted"),
                        html.H3(formatted["cagr"], style={"color": "#3fb950" if metrics["cagr"] > 0 else "#f85149"}),
                    ])
                ], style={"backgroundColor": "#161b22", "border": "1px solid #30363d", "borderRadius": "12px"}), width=3),
                dbc.Col(dbc.Card([
                    dbc.CardBody([
                        html.H6("Volatility", className="card-subtitle mb-2 text-muted"),
                        html.H3(formatted["volatility"]),
                    ])
                ], style={"backgroundColor": "#161b22", "border": "1px solid #30363d", "borderRadius": "12px"}), width=3),
                dbc.Col(dbc.Card([
                    dbc.CardBody([
                        html.H6("Sharpe Ratio", className="card-subtitle mb-2 text-muted"),
                        html.H3(formatted["sharpe_ratio"]),
                    ])
                ], style={"backgroundColor": "#161b22", "border": "1px solid #30363d", "borderRadius": "12px"}), width=3),
                dbc.Col(dbc.Card([
                    dbc.CardBody([
                        html.H6("Max Drawdown", className="card-subtitle mb-2 text-muted"),
                        html.H3(formatted["max_drawdown"], style={"color": "#f85149"}),
                    ])
                ], style={"backgroundColor": "#161b22", "border": "1px solid #30363d", "borderRadius": "12px"}), width=3),
            ], className="mb-4")

            charts = html.Div([
                dbc.Row([
                    dbc.Col(dcc.Graph(figure=price_chart(df, ticker=ticker, theme=theme, height=450, show_volume=True)), width=12),
                ], className="mb-4"),
                dbc.Row([
                    dbc.Col(dcc.Graph(figure=cumulative_returns_chart(df["Close"], ticker=ticker, theme=theme, height=400)), width=6),
                    dbc.Col(dcc.Graph(figure=drawdown_chart(df["Close"], ticker=ticker, theme=theme, height=400)), width=6),
                ], className="mb-4"),
                dbc.Row([
                    dbc.Col(dcc.Graph(figure=monthly_heatmap(df["Close"], ticker=ticker, theme=theme, height=400)), width=12),
                ])
            ])
            
            return summary, charts
        except Exception as e:
            return html.Div(f"Error: {e}", style={"color": "#f85149"}), []

    @app.callback(
        Output("compare-results", "children"),
        [Input("compare-btn", "n_clicks")],
        [State("tickers-input", "value"),
         State("compare-period-selector", "value"),
         State("global-theme-selector", "value")],
    )
    def update_compare(n_clicks, tickers_str, period, theme):
        if not tickers_str: return no_update
        tickers = [t.strip().upper() for t in tickers_str.split(",") if t.strip()]
        if len(tickers) < 2: return html.Div("Please enter at least two tickers.")
        
        try:
            data = fetch_multiple(tickers, period=period)
            prices_df = align_dataframes(data)
            
            perf_fig = performance_chart({t: prices_df[t] for t in tickers}, theme=theme, height=500)
            corr_fig = correlation_matrix(prices_df, theme=theme, height=500)
            
            return html.Div([
                dbc.Row([
                    dbc.Col(dcc.Graph(figure=perf_fig), width=12),
                ], className="mb-4"),
                dbc.Row([
                    dbc.Col(dcc.Graph(figure=corr_fig), width=12),
                ])
            ])
        except Exception as e:
            return html.Div(f"Error: {e}", style={"color": "#f85149"})

    return app


def render_single_tab():
    return html.Div([
        dbc.Row([
            dbc.Col([
                html.Label("Ticker Symbol", style={"color": "#8b949e", "fontSize": "11px", "textTransform": "uppercase"}),
                dbc.Input(id="ticker-input", value="AAPL", placeholder="e.g. BTC-USD, MSFT, AAPL", style={"backgroundColor": "#161b22", "border": "1px solid #30363d", "color": "#c9d1d9"}),
            ], width=3),
            dbc.Col([
                html.Label("Time Period", style={"color": "#8b949e", "fontSize": "11px", "textTransform": "uppercase"}),
                dbc.Select(
                    id="period-selector",
                    options=[
                        {"label": "1 Year", "value": "1y"},
                        {"label": "2 Years", "value": "2y"},
                        {"label": "5 Years", "value": "5y"},
                        {"label": "10 Years", "value": "10y"},
                        {"label": "Maximum", "value": "max"},
                    ],
                    value="5y",
                    style={"backgroundColor": "#161b22", "border": "1px solid #30363d", "color": "#c9d1d9"}
                ),
            ], width=2),
            dbc.Col([
                html.Br(),
                dbc.Button("Run Analysis", id="analyze-btn", color="primary", style={"width": "100%", "fontWeight": "600"}),
            ], width=2),
        ], className="mb-4 align-items-end"),
        
        html.Div(id="single-metrics-summary"),
        html.Div(id="single-charts-container"),
    ])


def render_compare_tab():
    return html.Div([
        dbc.Row([
            dbc.Col([
                html.Label("Tickers (comma separated)", style={"color": "#8b949e", "fontSize": "11px", "textTransform": "uppercase"}),
                dbc.Input(id="tickers-input", value="AAPL, MSFT, GOOGL", placeholder="e.g. AAPL, MSFT, GOOGL", style={"backgroundColor": "#161b22", "border": "1px solid #30363d", "color": "#c9d1d9"}),
            ], width=6),
            dbc.Col([
                html.Label("Time Period", style={"color": "#8b949e", "fontSize": "11px", "textTransform": "uppercase"}),
                dbc.Select(
                    id="compare-period-selector",
                    options=[
                        {"label": "1 Year", "value": "1y"},
                        {"label": "5 Years", "value": "5y"},
                        {"label": "10 Years", "value": "10y"},
                    ],
                    value="5y",
                    style={"backgroundColor": "#161b22", "border": "1px solid #30363d", "color": "#c9d1d9"}
                ),
            ], width=2),
            dbc.Col([
                html.Br(),
                dbc.Button("Compare Performance", id="compare-btn", color="success", style={"width": "100%", "fontWeight": "600"}),
            ], width=3),
        ], className="mb-4 align-items-end"),
        
        html.Div(id="compare-results"),
    ])
